name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: npm run test:integration
      env:
        IPREGISTRY_API_KEY:  ${{ secrets.IPREGISTRY_API_KEY }}
        IPREGISTRY_API_KEY_THROTTLED:  ${{ secrets.IPREGISTRY_API_KEY_THROTTLED }}
